.gitmodules: update maui submodule
Required changes for border fix and fixed window size.

Required changes for breaking words anywhere with dash.

Required changes for using dotnet 6.0.300.

We get an error trying to run Maui Frontend using gtk which
is as follows. Use forked maui since we were able to fix the
runtime font problem by modifing maui for gtk repository.

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 11:16. Type converter failed: The current platform does not implement the IFontNamedSizeService dependency service.
 ---> System.NotImplementedException: The current platform does not implement the IFontNamedSizeService dependency service.
   at Microsoft.Maui.Controls.Device.GetNamedSize(NamedSize size, Type targetElementType, Boolean useOldSizes) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Core/Device.cs:line 146
   at Microsoft.Maui.Controls.FontSizeConverter.Microsoft.Maui.Controls.IExtendedTypeConverter.ConvertFromInvariantString(String value, IServiceProvider serviceProvider) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Core/FontSizeConverter.cs:line 59
   at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Core/Xaml/TypeConversionExtensions.cs:line 164
   --- End of inner exception stack trace ---
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/ApplyPropertiesVisitor.cs:line 379
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/ApplyPropertiesVisitor.cs:line 62
   at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlNode.cs:line 92
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlNode.cs:line 153
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlNode.cs:line 155
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlNode.cs:line 212
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlLoader.cs:line 210
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Controls/src/Xaml/ViewExtensions.cs:line 37
   at GWallet.Frontend.Maui.WelcomePage..ctor(IGlobalAppState state) in /home/parham/Desktop/test-gee/gee2/src/GWallet.Frontend.Maui/WelcomePage.xaml.fs:line 22
   at GWallet.Frontend.Maui.WelcomePage..ctor() in /home/parham/Desktop/test-gee/gee2/src/GWallet.Frontend.Maui/WelcomePage.xaml.fs:line 112
   at GWallet.Frontend.Maui.App..ctor() in /home/parham/Desktop/test-gee/gee2/src/GWallet.Frontend.Maui/App.xaml.fs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Maui.MauiGtkApplication.StartupLauch(Object sender, EventArgs args) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 107
   at Microsoft.Maui.MauiGtkApplication.OnActivated(Object sender, EventArgs args) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 66
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.Run(String program_name, String[] args)
   at GLib.Application.Run()
   at Microsoft.Maui.MauiGtkApplication.Launch(EventArgs args) in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 127
   at Microsoft.Maui.MauiGtkApplication.Run() in /home/parham/Desktop/test-gee/gee2/dependencies/maui/src/Core/src/Platform/Gtk/MauiGtkApplication.cs:line 40
   at GWallet.Frontend.Maui.Program.main(String[] args) in /home/parham/Desktop/test-gee/gee2/src/GWallet.Frontend.Maui/Platforms/Gtk/Program.fs:line 14
```